#!/bin/sh

# Landscape (normal):

xrandr -o normal
xinput set-prop "pointer:ipts 045E:0021" --type=float "Coordinate Transformation Matrix" 0 0 0 0 0 0 0 0 0
xinput set-prop "Microsoft Surface Keyboard Touchpad" --type=float "Coordinate Transformation Matrix" 0 0 0 0 0 0 0 0 0
