#!/bin/sh

# Portrait (left):

xrandr -o left
xinput set-prop "pointer:ipts 045E:0021" --type=float "Coordinate Transformation Matrix" 0 -1 1 1 0 0 0 0 1
xinput set-prop "Microsoft Surface Keyboard Touchpad" --type=float "Coordinate Transformation Matrix" 0 -1 1 1 0 0 0 0 1
