#!/bin/sh

if [ ! "$(whoami)" = "root" ]; then
    echo "Please run as root."
    exit
fi

SYSLEEP="/usr/lib/systemd/system-sleep"

$SYSLEEP/reset_wifi.sh pre
sleep 1
$SYSLEEP/sleep pre
sleep 1
echo freeze > /sys/power/state
sleep 1
$SYSLEEP/sleep post
sleep 1
$SYSLEEP/reset_wifi.sh post

