#!/usr/bin/zsh

. $HOME/.profile

# Clear rules
bspc rule -r "*"

# Hotkey dæmon
pkill -x sxhkd
sxhkd &

# The cursor is a pesk
unclutter &
xbanish &

# West Arabic:  1 2 3 4 5 6 7 8 9 10
# Roman:        I II III IV V VI VII VIII IX X
# East Arabic:  ١ ٢ ٣ ٤ ٥ ٦ ٧ ٨ ٩ ١٠
# Chinese rods: 𝍠 𝍡 𝍢 𝍣 𝍤 𝍥 𝍦 𝍧 𝍨 𝍩
# Phoenician:   𐤖 𐤚 𐤛 𐤛𐤖 𐤛𐤚 𐤛𐤛 𐤛𐤛𐤖 𐤛𐤛𐤚 𐤛𐤛𐤛 𐤗
# Hebrew:       א ב ג ד ה ו ז ח ט י
# Chinese:      一二三四五六七八九十
# Indian Tamil: ௧ ௨ ௩ ௪ ௫ ௬ ௭ ௮ ௯ ௰
# Thai:         ๑ ๒ ๓ ๔ ๕ ๖ ๗ ๘ ๙ ๑๐
# Aegean:       𐄇 𐄈 𐄉 𐄊 𐄋 𐄌 𐄍 𐄎 𐄏 𐄐
# East Nagari:  ১ ২ ৩ ৪ ৫ ৬ ৭ ৮ ৯ ১০
# Malayalam:    ൧ ൨ ൩ ൪ ൫ ൬ ൭ ൮ ൯ ൰

WEST_ARABIC=(1 2 3 4 5 6 7 8 9 10)
ROMAN=(I II III IV V VI VII VIII IX X)
EAST_ARABIC=(١ ٢ ٣ ٤ ٥ ٦ ٧ ٨ ٩ ١٠)
CHINESE_RODS=(𝍠 𝍡 𝍢 𝍣 𝍤 𝍥 𝍦 𝍧 𝍨 𝍩)
PHOENICIAN=(𐤖 𐤚 𐤛 𐤛𐤖 𐤛𐤚 𐤛𐤛 𐤛𐤛𐤖 𐤛𐤛𐤚 𐤛𐤛𐤛 𐤗)
HEBREW=(א ב ג ד ה ו ז ח ט י)
CHINESE=(一 二 三 四 五 六 七 八 九 十)
INDIAN_TAMIL=(௧ ௨ ௩ ௪ ௫ ௬ ௭ ௮ ௯ ௰)
THAI=(๑ ๒ ๓ ๔ ๕ ๖ ๗ ๘ ๙ ๑๐)
AEGEAN=(𐄇 𐄈 𐄉 𐄊 𐄋 𐄌 𐄍 𐄎 𐄏 𐄐)
EAST_NAGARI=(১ ২ ৩ ৪ ৫ ৬ ৭ ৮ ৯ ১০)
MALAYALAM=(൧ ൨ ൩ ൪ ൫ ൬ ൭ ൮ ൯ ൰)

# Set workspace names
bspc monitor -d $CHINESE

# Window decoration
bspc config border_width 0
bspc config window_gap 40
bspc config top_padding 100
bspc config focus_follows_pointer true
bspc config focused_border_color "#657185"
bspc config normal_border_color  "#322f54"

# Let onscreen keyboard be floating
#bspc rule -a onboard state=floating
#bspc rule -a Onboard state=floating

# Display wallpaper
$HOME/.bin/display-wallpaper &

# Start bar
pkill polybar
sleep 0.2
. $HOME/.scripts/toggle-bar.sh &

# Start compositior
pkill -x compton
picom --config $HOME/.config/picom.conf \
   --experimental-backends --backend glx &

# Configure keyboard and mouse
setxkbmap -model pc105 -layout gb
xsetroot -cursor_name left_ptr

# Wifi card fix
eval 'sudo iw dev '{wlp1s0,mlan0}' set power_save off;'

# Touchpad Speed
xinput set-prop \
    "Microsoft Surface Keyboard Touchpad" \
    "libinput Accel Speed" 0.9

# Set orientation
if [ "$(sys-conf get orientation)" = portrait ]; then
    rotate-portrait
fi

# Set window rules
bspc rule -a Chromium desktop='^2'

# Open startup applications
. $HOME/.scripts/startup.sh

# Switch to ^1 and refresh borders
sleep 0.2
bspc desktop -f '^1'
sleep 0.2

# Finally apply border radius
bspc config border_radius 19

~/.scripts/border-refresh.sh

echo "$XDG_CURRENT_DESKTOP" >> ~/.bspwm.out
/usr/lib/deepin-daemon/dde-osd & 2>> ~/.bspwm.out
